

-- 1.
SELECT *
FROM JOB;

-- 2.
SELECT JOB_NAME
FROM JOB;

-- 3.
SELECT *
FROM DEPARTMENT;

-- 4.
SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE
FROM EMPLOYEE;

--5.
SELECT HIRE_DATE, EMP_NAME, SALARY
FROM EMPLOYEE;

-- 6. 이거 보너스 없는애들 다시해봐야될듯
SELECT EMP_NAME, SALARY*12, (SALARY + SALARY * BONUS)*12 AS "총수령액",
      (SALARY + SALARY * BONUS)*12 - (SALARY*12*0.03) AS "실수령액"
FROM EMPLOYEE;

-- 7.
SELECT EMP_NAME, SALARY, HIRE_DATE, PHONE
FROM EMPLOYEE
WHERE SAL_LEVEL = 'S1';

-- 8.
SELECT EMP_NAME, SALARY, (SALARY + SALARY * BONUS)*12 - (SALARY*12*0.03) AS "실수령액",
       HIRE_DATE
FROM EMPLOYEE
WHERE (SALARY + SALARY * BONUS)*12 - (SALARY*12*0.03)>= 50000000;

-- 9.
SELECT *
FROM EMPLOYEE
WHERE SALARY >= 4000000 AND JOB_CODE = 'J2';

-- 10.
SELECT EMP_NAME, DEPT_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE = 'D9' OR DEPT_CODE = 'D5') AND HIRE_DATE < '02/01/01';

-- 11.
SELECT *
FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN '90/01/01' AND '01/01/01';

-- 12.
SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_NAME LIKE '%연';

-- 13. NULL값 포함함
SELECT EMP_NAME, PHONE
FROM EMPLOYEE
WHERE PHONE NOT LIKE '010%' OR PHONE IS NULL;

-- 14.
SELECT *
FROM EMPLOYEE
WHERE EMAIL LIKE '____#_%' ESCAPE '#' AND (DEPT_CODE = 'D9' OR DEPT_CODE = 'D6')
AND (HIRE_DATE BETWEEN '90/01/01' AND '00/12/01') AND SALARY >= 2700000;

-- 15.
SELECT EMP_NAME, 
EXTRACT(YEAR FROM HIRE_DATE) AS "입사년도",
EXTRACT(MONTH FROM HIRE_DATE) AS "입사월",
EXTRACT(DAY FROM HIRE_DATE) AS "입사일"
FROM EMPLOYEE;

-- 16.


SELECT *
FROM EMPLOYEE




