-- Basic SELECT
-- 1.

SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS "계열"
FROM TB_DEPARTMENT;

-- 2.
SELECT DEPARTMENT_NAME||'의 정원은 ' || CAPACITY || ' 명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

-- 3. ㄱㄷㄱㄷ
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y' AND DEPARTMENT_NO = '001'
AND SUBSTR(STUDENT_SSN,8,1) IN ('2','4');

-- 4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;

-- 5.
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY >= 20 AND CAPACITY <= 30;

-- 6.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7.
SELECT *
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8.
SELECT PREATTENDING_CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9.
SELECT CATEGORY
FROM TB_DEPARTMENT
GROUP BY CATEGORY
ORDER BY CATEGORY;

-- 10.
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE INSTR(STUDENT_ADDRESS,'전주') > 0 
AND EXTRACT(YEAR FROM ENTRANCE_DATE)= '2002'
AND ABSENCE_YN = 'N';

-- Additional SELECT - 함수
-- 1.
SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 2
ORDER BY ENTRANCE_DATE;

-- 2. 잘 작성해서 문제가 없네요 ㅋ
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3.
SELECT PROFESSOR_NAME AS "교수이름",
TO_NUMBER(TO_CHAR(SYSDATE,'RR')) - TO_NUMBER(SUBSTR(PROFESSOR_SSN,1,2))+100
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1;

-- 4.
SELECT SUBSTR(PROFESSOR_NAME,2) AS "이름"
FROM TB_PROFESSOR;

-- 5.
SELECT STUDENT_NO, STUDENT_NAME, SUBSTR(STUDENT_SSN,1,6)
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)-
EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6))) >= 20;

-- 6.
SELECT TO_CHAR(TO_DATE('20/12/25'), 'DAY')
FROM DUAL;

-- 7.
TO_DATE('99/10/11','YY/MM/DD');
-- 2099년 10월 11일
TO_DATE('49/10/11','YY/MM/DD');
-- 1949년 10월 11일
TO_DATE('99/10/11','RR/MM/DD');
-- 1999년 10월 11일

-- 8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) <> 'A';

-- 9.
SELECT ROUND(AVG(POINT),1) AS "평점"
FROM  TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10.
SELECT DEPARTMENT_NO AS "학과번호", COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12.
SELECT SUBSTR(TERM_NO,1,4) AS "년도", ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4);

-- 13. 어쩌란거야
SELECT DEPARTMENT_NO, COUNT(*)
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 14.
SELECT STUDENT_NAME AS "동일이름", COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME;






SELECT *
FROM TB_CLASS_PROFESSOR;

SELECT *
FROM TB_PROFESSOR;

SELECT *
FROM TB_STUDENT;

SELECT *
FROM TB_GRADE;

