SELECT * FROM TB_BOOK;
SELECT * FROM TB_WRITER;
SELECT * FROM TB_PUBLISHER;
SELECT * FROM TB_BOOK_AUTHOR;

-- 3.
SELECT BOOK_NO, BOOK_NM
FROM TB_BOOK
WHERE LENGTH(BOOK_NM) >= 25;

-- 4.
SELECT WRITER_NM, OFFICE_TELNO, HOME_TELNO, MOBILE_NO
FROM TB_WRITER
WHERE MOBILE_NO LIKE '019%' AND WRITER_NM LIKE '김%';

-- 5.
SELECT COUNT(COUNT(*)) AS "작가(명)"
FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE = '옮김'
GROUP BY WRITER_NO;

-- 6.
SELECT COMPOSE_TYPE, COUNT(COMPOSE_TYPE)
FROM TB_BOOK_AUTHOR
GROUP BY COMPOSE_TYPE
HAVING COUNT(COMPOSE_TYPE) >= 300;

-- 7.
SELECT BOOK_NM, ISSUE_DATE, PUBLISHER_NM
FROM(SELECT *
        FROM TB_BOOK
        ORDER BY ISSUE_DATE DESC)
WHERE ROWNUM <= 1;

-- 8.
SELECT WRITER_NM, 수량
FROM (SELECT WRITER_NO, COUNT(*) AS "수량"
        FROM TB_BOOK_AUTHOR
        GROUP BY WRITER_NO
        ORDER BY COUNT(*) DESC)
JOIN TB_WRITER USING(WRITER_NO)
WHERE ROWNUM <= 3;

-- 9.

/*
UPDATE 테이블명
    SET 컬럼명 = 바꿀값,
        컬럼명 = 바꿀값,
        ...         -> 여러개의 컬럼값 동시변경 가능(,로 나열해야됨! AND 아님!)
    [WHERE 조건];    -> 생략하면 전체 행의 모든 행의 데이터가 변경된다. 그래서 꼭 조건을 써줘야함
*/

INSERT INTO 테이블명 (컬럼명, 컬럼명, 컬럼명) VALUES (값1, 값2, 값3);

INSERT INTO TB_WRITER (REGIST_DATE) VALUES (SELECT MIN(ISSUE_DATE)
FROM TB_BOOK
JOIN TB_BOOK_AUTHOR USING(BOOK_NO)
JOIN TB_WRITER USING(WRITER_NO)
GROUP BY WRITER_NM);

UPDATE TB_WRITER W
SET REGIST_DATE = (SELECT MIN(ISSUE_DATE)
FROM TB_BOOK
JOIN TB_BOOK_AUTHOR USING(BOOK_NO)
JOIN TB_WRITER USING(WRITER_NO)
WHERE W.WRITER_NO = WRITER_NO);


--DEFAULT값 수정       : MODIFY 컬럼명 DEFAULT 바꾸고자하는 기본 값

;
SELECT WRITER_NM, MIN(ISSUE_DATE)
FROM TB_BOOK
JOIN TB_BOOK_AUTHOR USING(BOOK_NO)
JOIN TB_WRITER USING(WRITER_NO)
GROUP BY WRITER_NM;

-- 10.
CREATE TABLE TB_BOOK_TRANSLATOR(
    BOOK_NO VARCHAR2(10) CONSTRAINT FK_BOOK_TRANSLATOR_01 REFERENCES TB_BOOK,
    WRITER_NO VARCHAR2(10) CONSTRAINT FK_BOOK_TRANSLATOR_02 REFERENCES TB_WRITER,
    TRANS_LANG VARCHAR2(60), 
    CONSTRAINT PK_BOOK_TRANSLATOR PRIMARY KEY(BOOK_NO, WRITER_NO)
);

-- 11.
INSERT INTO TB_BOOK_TRANSLATOR (BOOK_NO, WRITER_NO)
                                (SELECT BOOK_NO, WRITER_NO
                                FROM TB_BOOK_AUTHOR
                                WHERE COMPOSE_TYPE IN ('옮김','역주','편역','공역'));

-- 12.
-- ISSUE_DATE
-- TB_BOOK_TRANSLATOR / BOOK_NO, WRITER_NO
-- TB_BOOK / BOOK_NO
-- TB_WRITER / WRITER_NO


SELECT BOOK_NM, WRITER_NM, ISSUE_DATE
FROM TB_BOOK
JOIN TB_BOOK_TRANSLATOR USING (BOOK_NO)
JOIN TB_WRITER USING (WRITER_NO)
WHERE EXTRACT(YEAR FROM ISSUE_DATE) = 2007;

COMMIT;
-- 13.

CREATE OR REPLACE VIEW VW_BOOK_TRANSLATOR
AS SELECT BOOK_NM, WRITER_NM, ISSUE_DATE
    FROM TB_BOOK
    JOIN TB_BOOK_TRANSLATOR USING (BOOK_NO)
    JOIN TB_WRITER USING (WRITER_NO)
    WHERE EXTRACT(YEAR FROM ISSUE_DATE) = 2007
WITH READ ONLY;


GRANT CREATE VIEW TO final;

-- 14.
INSERT INTO TB_PUBLISHER
VALUES ('춘 출판사', '02-6710-3737', DEFAULT);

-- 15.
SELECT WRITER_NM, COUNT(*)
FROM TB_WRITER
GROUP BY WRITER_NM
HAVING COUNT(*)>=2;

-- 16.
INSERT INTO TB_BOOK_AUTHOR (COMPOSE_TYPE)
(SELECT NVL(COMPOSE_TYPE,'지음')
FROM TB_BOOK_AUTHOR);

UPDATE TB_BOOK_AUTHOR
SET COMPOSE_TYPE = '지음'
WHERE COMPOSE_TYPE IS NULL;
COMMIT;

-- 17.
SELECT WRITER_NM, OFFICE_TELNO
FROM TB_WRITER
WHERE OFFICE_TELNO LIKE '02_________';

-- 18.
SELECT WRITER_NM
FROM TB_WRITER
WHERE MONTHS_BETWEEN('06/01/01',REGIST_DATE) >= 31*12
ORDER BY WRITER_NM;

-- 19.
ALTER TABLE TB_BOOK ADD HOWMANY VARCHAR(20);

INSERT INTO TB_BOOK (HOWMANY)




SELECT STOCK_QTY
FROM TB_BOOK
WHERE PUBLISHER_NM = '황금가지';


INSERT INTO TB_BOOK_AUTHOR (COMPOSE_TYPE)
(SELECT NVL(COMPOSE_TYPE,'지음')
FROM TB_BOOK_AUTHOR);

-- 20.
-- TB_BOOK_TRANSLATOR/WRITER_NO -> WRITER_NM 

SELECT BOOK_NM, WRITER_NM
FROM TB_WRITER
JOIN TB_BOOK_AUTHOR USING(WRITER_NO)
JOIN TB_BOOK USING(BOOK_NO)
WHERE BOOK_NM = '아타트롤'
GROUP BY BOOK_NM, WRITER_NM;


-- 21.
-- REGIST_DATE , SYSDATE 





SELECT * FROM TB_BOOK;
SELECT * FROM TB_WRITER;
SELECT * FROM TB_PUBLISHER;
SELECT * FROM TB_BOOK_AUTHOR;
SELECT * FROM TB_BOOK_TRANSLATOR;























